"""Generate a deterministic, self-contained source image. No code is imported.

The generated entry is a reviewed trust anchor, NOT a self-authenticating file.
Source release provenance must bind its bytes externally before preparation.
"""
import argparse
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]


def render():
    version = tomllib.loads((ROOT / 'pyproject.toml').read_text())['project']['version']
    sources = {}
    for path in sorted((ROOT / 'trojaino').rglob('*.py')):
        if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
            raise ValueError('linked source rejected')
        parts = path.relative_to(ROOT).with_suffix('').parts
        name = '.'.join(parts[:-1] if parts[-1] == '__init__' else parts)
        sources[name] = path.read_text(encoding='utf-8')
    # The source package initializer discovers installed metadata. Sealed images
    # deliberately replace ONLY this initializer with a literal build version.
    sources['trojaino'] = '__version__ = ' + repr(version) + '\n'
    capsule = {'version': version, 'sources': sources,
               'bootstrap': (ROOT / 'scripts/sealed_runtime_bootstrap.py').read_text()}
    return ("# Generated by scripts/build_sealed_runtime.py; do not edit.\n"
            "import sys\n"
            "if sys.version_info < (3, 11) or not sys.flags.isolated or not sys.flags.no_site:\n"
            "    raise SystemExit(2)\n"
            "from pathlib import Path\n"
            "_entry = Path(__file__).absolute()\n"
            "if _entry.is_symlink():\n"
            "    print('{\"decision\":\"deny\",\"reason\":\"plugin_entry_invalid\"}')\n"
            "    raise SystemExit(2)\n"
            "_EXPECTED_BINDING = None\n"
            "if _EXPECTED_BINDING is not None and (str(_entry), str(Path(sys.executable).resolve())) != _EXPECTED_BINDING:\n"
            "    print('{\"decision\":\"deny\",\"reason\":\"prepared_binding_mismatch\"}')\n"
            "    raise SystemExit(2)\n"
            "import os\n"
            "_plugin_root = os.environ.get('CLAUDE_PLUGIN_ROOT')\n"
            "if _EXPECTED_BINDING is not None and _plugin_root is not None and _plugin_root != str(_entry.parent.parent):\n"
            "    print('{\"decision\":\"deny\",\"reason\":\"prepared_plugin_root_mismatch\"}')\n"
            "    raise SystemExit(2)\n"
            "_CAPSULE = " + repr(capsule) + "\n"
            "_CAPSULE['entry'] = str(_entry)\n"
            "exec(compile(_CAPSULE['bootstrap'], '<sealed-bootstrap>', 'exec'))\n")


def build(output):
    Path(output).write_text(render(), encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    build(parser.parse_args().output)
