"""Generate a deterministic, self-contained scanner image. No code is imported.

The generated entry is the plugin's only executable file. It carries the whole
scanner as data and imports nothing from disk, so it works from wherever
Claude Code installs the plugin.
"""
from __future__ import annotations

import argparse
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent.parent
BOOTSTRAP = Path(__file__).resolve().parent / 'sealed_runtime_bootstrap.py'
# Packaging helpers are not part of the runtime image.
EXCLUDED_SUBPACKAGES = ('claude',)


def version() -> str:
    """Prefer the committed value in a checkout; fall back to installed metadata."""
    pyproject = PACKAGE.parent / 'pyproject.toml'
    if pyproject.is_file():
        import tomllib
        return tomllib.loads(pyproject.read_text(encoding='utf-8'))['project']['version']
    from importlib.metadata import version as installed_version
    return installed_version('trojaino')


def source_map() -> dict[str, str]:
    sources: dict[str, str] = {}
    for path in sorted(PACKAGE.rglob('*.py')):
        if path.is_symlink() or any(parent.is_symlink() for parent in path.parents):
            raise ValueError('linked source rejected')
        parts = path.relative_to(PACKAGE).with_suffix('').parts
        if parts[0] in EXCLUDED_SUBPACKAGES:
            continue
        stem = parts[:-1] if parts[-1] == '__init__' else parts
        sources['.'.join(('trojaino',) + stem)] = path.read_text(encoding='utf-8')
    return sources


def render() -> str:
    sources = source_map()
    # The source package initializer discovers installed metadata. Sealed images
    # deliberately replace ONLY this initializer with a literal build version.
    build_version = version()
    sources['trojaino'] = '__version__ = ' + repr(build_version) + '\n'
    capsule = {'version': build_version, 'sources': sources,
               'bootstrap': BOOTSTRAP.read_text(encoding='utf-8')}
    return ("# Generated by trojaino.claude.seal; do not edit.\n"
            "import sys\n"
            "if sys.version_info < (3, 11) or not sys.flags.isolated or not sys.flags.no_site:\n"
            "    sys.stderr.write('Trojaino needs Python 3.11 or newer, run with -I -S.\\n')\n"
            "    raise SystemExit(1)\n"
            "from pathlib import Path\n"
            "_entry = Path(__file__).absolute()\n"
            "_CAPSULE = " + repr(capsule) + "\n"
            "_CAPSULE['entry'] = str(_entry)\n"
            "exec(compile(_CAPSULE['bootstrap'], '<sealed-bootstrap>', 'exec'))\n")


def build(output) -> None:
    Path(output).write_text(render(), encoding='utf-8')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    build(parser.parse_args().output)
